name: Node.js CI and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to Server using Docker Compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: 43.218.137.88
        username: ubuntu
        port: 22
        script: cd /home/ubuntu/docker-tes && git pull origin main && docker compose up
