name: Node.js CI and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to Server using Docker Compose
      run: |
        ssh -i /.github/website_cyber2.pem ubuntu@43.218.137.88 "cd /home/ubuntu/docker-test && docker compose up"
