name: Node.js CI and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code and deploy
      uses: actions/checkout@v2
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Deploy to Server
      run: |
        ssh ubuntu@43.218.137.88 "cd /home/docker-tes && git pull origin main && npm install && npm run build && pm2 restart your-app"
